### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gerbilsinspace** [pikselpalette/sequoia-java-client-sdk#1]
What license is this released under?

**Comment by juanluhidalgo** [comment]
Hi,

This is the license https://github.com/pikselpalette/sequoia-java-client-sdk/blob/master/pom.xml#L18 

anyway we're gonna add the LICENSE file

**Comment by juanluhidalgo** [comment]
LICENSE added https://github.com/pikselpalette/sequoia-java-client-sdk/commit/b2590dc2a0aa27adacb59c756deaeda242739326
